apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: azhz
  azurestorageaccountkey: VjFZQ3BORG1nQlNQVTdJOHo2VWNNTldDOUlZVnRLTWZlb2VDYlI0ekl6OUg2VUdvbE9qYkoxUGYrbWhmdHlmWCtwZ1Q2b1MyODB2akVrMVF3WlUrckE9PQ==
