apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: azhz
  azurestorageaccountkey: YWNYZFR4TnVHaDNSZnZ5elRDanU0YnVvZk9TbzNpc3RjejM2NzZTK1Q2NkRUbXJjZ04zSlpSWU9zdmVZTHh5T1RVcUZrTVBMYkw0RkVrMUo5QTFCVHc9PQ==
