apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: minecraft-deployment
  name: minecraft-deployment-pod
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: minecraft-deployment-app
    spec: 
      containers: 
        - env: 
            - name: EULA
              value: "TRUE"
          image: "openhack/minecraft-server:2.0"
          name: minecraft-container
          ports: 
            - containerPort: 25565
            - containerPort: 25575
          volumeMounts: 
            - mountPath: /data
              name: azure
      volumes: 
        - azureFile: 
            readOnly: false
            secretName: azure-secret
            shareName: mcdata
          name: azure
