apiVersion: v1
kind: Service
metadata:
  name: minecraft-app-service
spec:
  selector:
    app: minecraft-deployment-app
  ports:
  - port: 25565
    targetPort: 25565
  - port: 25575
    targetPort: 25575
  type: LoadBalancer
